# Generated by Django 6.0.1 on 2026-02-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(help_text='Full name of the person')),
                ('acdc_email', models.TextField(blank=True, help_text='ACDC email address', null=True, unique=True)),
                ('personal_email', models.TextField(blank=True, help_text='Personal email address', null=True, unique=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('member_type', models.CharField(choices=[('employee', 'Employee'), ('volunteer', 'Volunteer')], default='employee', help_text='Whether this person is an employee or a volunteer', max_length=20)),
                ('department', models.TextField(choices=[('Engineering', 'Engineering'), ('Product Management', 'Product Management'), ('Design', 'Design'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Executive', 'Executive'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance')], help_text='Department (required)')),
                ('subteam', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, choices=[('Volunteer', 'Volunteer'), ('Asst. Director', 'Asst. Director'), ('Director', 'Director')], help_text='Position/Role', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', help_text='Member status', max_length=20)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('reports_to', models.TextField(blank=True, choices=[('Director', 'Director'), ('Asst. Director', 'Asst. Director'), ('Jenny', 'Jenny')], help_text='Reporting manager', null=True)),
                ('time_commitment', models.SmallIntegerField(blank=True, help_text='Time commitment in hours (0-80)', null=True)),
                ('portal_email', models.TextField(blank=True, help_text='Login email for HR portal', null=True)),
                ('portal_role', models.CharField(blank=True, help_text='Role in HR portal', max_length=50, null=True)),
                ('portal_password', models.TextField(blank=True, help_text='TEMPORARY: plain password set by HR', null=True)),
                ('start_date', models.DateField(help_text='Start date (required)')),
                ('end_date', models.DateField(blank=True, help_text='End date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'people',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['status'], name='people_status_175f4e_idx'), models.Index(fields=['department', 'subteam'], name='people_departm_075019_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('time_commitment__gte', 0), ('time_commitment__lte', 80)), name='time_commitment_range')],
            },
        ),
    ]
