# Generated by Django 5.2.6 on 2026-02-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.TextField(blank=True, choices=[('Volunteer', 'Volunteer'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('Asst. Director', 'Asst. Director'), ('Director', 'Director')], help_text='Position/Role', null=True),
        ),
    ]
